# Generated by Django 2.1 on 2018-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_accounts',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('total_votes', models.IntegerField(default=0)),
                ('bot_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
