# Generated by Django 2.1 on 2018-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_accounts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('total_votes', models.IntegerField(default=0)),
                ('bot_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
