# Generated by Django 2.1 on 2018-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter_account',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('bot_votes', models.IntegerField(default=0)),
                ('answer_1_votes', models.IntegerField(default=0)),
                ('answer_2_votes', models.IntegerField(default=0)),
                ('answer_3_votes', models.IntegerField(default=0)),
                ('answer_4_votes', models.IntegerField(default=0)),
                ('answer_5_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
