# Generated by Django 2.1 on 2018-08-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_twitter_account_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_account',
            name='screen_name',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
