# Generated by Django 2.1 on 2018-09-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_twitter_account_classified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
