# Generated by Django 2.1 on 2018-08-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_twitter_account_image_url'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_account',
            field=models.ForeignKey(default=0, on_delete=None, to='profiles.Twitter_account'),
            preserve_default=False,
        ),
    ]
