# Generated by Django 2.1 on 2018-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_vote_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vote_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='profiles.Twitter_account'),
        ),
    ]
